// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGZmvnVl49y8jt7fakAwytNCS-kfKe2WA',
    appId: '1:474672548117:web:9c2e6b321b130e7ff3c11c',
    messagingSenderId: '474672548117',
    projectId: 'switchn-clone',
    authDomain: 'switchn-clone.firebaseapp.com',
    storageBucket: 'switchn-clone.firebasestorage.app',
    measurementId: 'G-JWGZB6YZ09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTlRmB7JWZpfjZDoVQLDTxcvcmJqAT0TE',
    appId: '1:474672548117:android:1aa766ebf8d54d20f3c11c',
    messagingSenderId: '474672548117',
    projectId: 'switchn-clone',
    storageBucket: 'switchn-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3_bhwSZbk6S2M44B6a9nrRnTaLwoFj9w',
    appId: '1:474672548117:ios:f5c75b36b50ec770f3c11c',
    messagingSenderId: '474672548117',
    projectId: 'switchn-clone',
    storageBucket: 'switchn-clone.firebasestorage.app',
    iosBundleId: 'com.example.switchn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3_bhwSZbk6S2M44B6a9nrRnTaLwoFj9w',
    appId: '1:474672548117:ios:f5c75b36b50ec770f3c11c',
    messagingSenderId: '474672548117',
    projectId: 'switchn-clone',
    storageBucket: 'switchn-clone.firebasestorage.app',
    iosBundleId: 'com.example.switchn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGZmvnVl49y8jt7fakAwytNCS-kfKe2WA',
    appId: '1:474672548117:web:4e4d01788711669af3c11c',
    messagingSenderId: '474672548117',
    projectId: 'switchn-clone',
    authDomain: 'switchn-clone.firebaseapp.com',
    storageBucket: 'switchn-clone.firebasestorage.app',
    measurementId: 'G-9Y4MYBBCXL',
  );

}